### ISSUE TITLE
AEproejct Contract Injector & Development Frameworks Library

### ISSUE THREAD

**Issue by HristiyanG** [aeternity/aeproject#318]

**Comment by HristiyanG** [comment]
in order to complete the epic story, we'd need to complete those:

write contract functionalities (Ownable, FungibleToken, Non-Fungible Token, Crowdsale, etc)
write actual implementation for inclusion in existing contracts
add CLI command which will inject the functionality
add the upper snippets on aeproject init
add the snippet to the contract
add documentation

**Comment by marc0olo** [comment]
cleaning up old issues. feel free to re-open if still relevant
