### ISSUE TITLE
[BUG] aeproject compile problem

### ISSUE THREAD

**Issue by Vishwas1** [aeternity/aeproject#345]
**Describe the bug**
Some packages are missing

**To Reproduce**
1. npm i  -g aeproject
2. aeproject init
3. aeproject compile

**Expected behavior**
Should be able to compile the template project 

**Aeproject information (please complete the following information):**
 - OS executed at: Ubuntu 18.04
 - AEproject Version [e.g. @2.2.0]

**Additional context**
Please add  these packages
```
 "aeproject-logger": "^2.2.0",
  "aeproject-utils": "^2.2.0",
  "prompts": "^2.3.1"
```

**Comment by mradkov** [comment]
Is this still reproducible with https://github.com/aeternity/aepp-aeproject-js/releases/tag/v3.0.4?

**Comment by marc0olo** [comment]
should definitely we solved already. also there is `v4.0.0` upcoming shortly which can already be tested with [4.0.0-beta.1](https://www.npmjs.com/package/@aeternity/aeproject/v/4.0.0-beta.1)
