### ISSUE TITLE
[FEATURE] allow to set number of funded accounts

### ISSUE THREAD

**Issue by thepiwo** [aeternity/aeproject#346]
**Describe the solution you'd like**
allow to set number of funded accounts

**Additional context**
can be used for performance improvements in CI

**Comment by mradkov** [comment]
This is already possible in the config/wallets.

**Comment by marc0olo** [comment]
@thepiwo do we want to improve here anything in that regards? currently we have a set of 10 accounts pre-funded with start of devmode, right? can we close this?

**Comment by thepiwo** [comment]
we have any number of accounts as specified in the accounts.json
