### ISSUE TITLE
Aeproject-utils read dependency from word "namespace" instead of start of the file[BUG]

### ISSUE THREAD

**Issue by genievot** [aeternity/aeproject#365]
**Describe the bug**
When I create a namespace in a separate file and include it in the contract. The namespace file read & matched with regex by the aeproject-utils  https://github.com/aeternity/aepp-aeproject-js/blob/2c015c5c23205ee0fd90e180bf649cb71f79b8a9/packages/aeproject-utils/utils/aeproject-utils.js#L208 outputs dependency contract (namespace) starting from the word namespace and skips everything else define on top of it. 
https://github.com/aeternity/aepp-aeproject-js/blob/2c015c5c23205ee0fd90e180bf649cb71f79b8a9/packages/aeproject-utils/utils/aeproject-utils.js#L275

**For example**:

```
contract OracleConnector =
    entrypoint createOracle : (bytes(32), int, int) => bool
    entrypoint query: (string) => bytes(32)
    entrypoint canCallBack: () => bool

contract OracleAddressResolver =
    entrypoint getAddress : () => address
namespace Say =
    public function getOracleAddress() : address =
        let ar : OracleAddressResolver = ct_xRAL2ZaqffbTAeQrAunrR8jxdg9YbJvuEnFFJC8g8oW4LJ7Um
        ar.getAddress()
        

contract Boolean = // This part relates to another bug...
  record boolean = {
    ok: bool
   }
 ```
and included in a contract:
```
include "./libs/Say.aes"
contract MyContract =
    public entrypoint plus() : address =
      Say.getOracleAddress()
        
 ```
Will be returned with:  (missing `OracleConnector` & `OracleAddressResolver`)

```
{
  code: 'include "./libs/Say.aes"\n' +
    'contract MyContract =\n' +
    '    public entrypoint plus() : address =\n' +
    '      Say.getOracleAddress()\n' +
    '        ',
  options: {
    file_system: {
      './libs/Say.aes': 'namespace Say =\n' +
        '    public function getOracleAddress() : address =\n' +
        '        let ar : OracleAddressResolver = ct_xRAL2ZaqffbTAeQrAunrR8jxdg9YbJvuEnFFJC8g8oW4LJ7Um\n' +
        '        ar.getAddress()\n' +
        '        \n' +
        '\n' +
        'contract Boolean =\n' +
        '  record boolean = {\n' +
        '    ok: bool\n' +
        '   }'
    }
  }
}
```

> The issue results in not being able to identify the above-declared types.
------

**To Reproduce**

1. Create a namespace inside aeproject (Use any compiler version you like)
2. Include that namespace
3. Run `aeproject compile`
------

**Expected behavior**
It should compile successfully just with above code in the **Describe the Bug** section.

------
**Screenshots**
As said that the issue results in errors of unbounded types:
![image](https://user-images.githubusercontent.com/40867747/116911301-4f2d2d80-ac64-11eb-9ad3-b991b2b40466.png)

------

**Aeproject information (please complete the following information):**
 - OS executed at: Ubuntu 20
 - AEproject Version: Latest as of today.

------
**Additional context**
To make it working. I had to add a dummy namespace at top of the file
Please visit here to see more info on the issue: https://forum.aeternity.com/t/using-namespace-as-api/9321/12?u=genievot

**Comment by marc0olo** [comment]
@genievot the behavior changed here a lot. can you check if this problem still exists with [4.0.0-beta.1](https://www.npmjs.com/package/@aeternity/aeproject/v/4.0.0-beta.1)?

I am closing this for now. feel free to re-open if the problem still exists
