### ISSUE TITLE
While using inbuilt libraries, It throw `File Not Found Error`

### ISSUE THREAD

**Issue by genievot** [aeternity/aeproject#371]
**Describe the bug**
In the Current version of the Ae project: While using inbuilt libraries, It throws `File Not Found Error`. For example, if you want to include String.aes and then try to compile it. The file read (As I assume) if found statement after `include` It tries to read the file from directory path as given, It works if you use custom libraries that are saved locally.

**To Reproduce**
1. Create new contract with `include String.aes` (As an example)
2. Then perform compilation `aeproject compile`
3. You can find the error listed.

`File to include 'String.aes' not found. Check your path or it is from Sophia default library .`

**Expected behavior**
It should work without creating a file for the inbuilt library so no need to find the code to paste in it. Since everything will be compiled on the server compiler (local or remote), There requires a check for inbuilt libraries that if it found one, For e.g. `Oracle.aes` It shouldn't perform file system read operation on it.

**Aeproject information (please complete the following information):**
 - OS executed at: Ubuntu 20
 - AEproject Version: Latest as of Today.

**Comment by mradkov** [comment]
Should be fixed with 3.0.4. Please let us know if you have any further issues with it.

**Comment by genievot** [comment]
Thank you.
