### ISSUE TITLE
[BUG] Iris-Compatibility issue with M1 Mac and docker container 

### ISSUE THREAD

**Issue by omar-saadoun** [aeternity/aeproject#376]
**Describe the bug**
When starting the environment as usual with **aeproject env** it get stopped when starting the node and funding wallets.

Checking on logs for the node I get this:

Exec: /home/aeternity/node/erts-10.7.2.3/bin/erlexec -boot /home/aeternity/node/releases/6.0.0-rc3/aeternity -mode embedded -boot_var SYSTEM_LIB_DIR /home/aeternity/node/lib -config /home/aeternity/node/releases/6.0.0-rc3/sys.config -args_file /home/aeternity/node/releases/6.0.0-rc3/vm.args -- console -noinput -aehttp enable_debug_endpoints true
Root: /home/aeternity/node
/home/aeternity/node
sigaltstack: Invalid argument
sigaltstack: Invalid argument
qemu: uncaught target signal 6 (Aborted) - core dumped

Doing some research it seems that there is some issue between OTP version, docker and M1 Mac processors.

https://github.com/docker/for-mac/issues/5148
 
**Aeproject information (please complete the following information):**
 - OS executed at: MacOS M1 processor
 - AEproject Version @3.0.0 beta version

**Comment by mradkov** [comment]
This is a problem with the node itself as you already mentioned here https://github.com/aeternity/aeternity/issues/3632.

**Comment by marc0olo** [comment]
should be fixed if https://github.com/aeternity/aeternity/issues/3846 is solved and a new release is published afterwards

**Comment by marc0olo** [comment]
actually we already have a working image.

@omar-saadoun @thepiwo is this m1 image somewhere public and can be explicitly manually set by users?

**Comment by thepiwo** [comment]
As far as I know there hasn't been a production read image been published yet

**Comment by marc0olo** [comment]
didn't you publish this workaround image somewhere? just in case somebody really wants to play around with it

**Comment by omar-saadoun** [comment]
I'm playing around with it

**Comment by thepiwo** [comment]
Its finally fixed using aeproject 4.6.0 https://github.com/aeternity/aeproject/releases/tag/v4.6.0
