### ISSUE TITLE
[BUG] Error at Importing Aepp-Sdk when running `aeproject test`

### ISSUE THREAD

**Issue by genievot** [aeternity/aeproject#392]
**Describe the bug**
When I ran `aeproject test` on the default aeproject (exampleTests.js file), Then I got an error that looks like [1]
However, a little bit of tracking got me to realize that it is in the `util` script from **aeproject** module when importing **aepp-sdk** [2]. The whole script `ae-sdk.js` is getting printed on the console which makes it harder to locate the actual errors on less precise terminal windows.

**To Reproduce**
1. Initialize the AEproject project `aeproject init`
2. Start the node with `aeproject env`
3. Run the tests with `aeproject test`
4. See the error

**Expected behavior**
It should work fine.

**Screenshots**
**[1]**
![image](https://user-images.githubusercontent.com/40867747/147363261-e77fa162-ea0a-4648-8fa5-bbc78d87f005.png)

**[2]**
![image](https://user-images.githubusercontent.com/40867747/147363125-e5451c66-0992-4076-a5cf-8472a8267c60.png)

**Aeproject information (please complete the following information):**
 - OS executed at: [Ubuntu 20.04.2 LTS]
 - AEproject Version [^4(alpha)]
 - AEsdk Version [^10]

**Comment by genievot** [comment]
Thanks to @omar-saadoun  message on discord, This is solved by me as well by upgrading node to older LTS (12) to newer LTS (16).

**Comment by davidyuk** [comment]
This is also being solved on the sdk side in:
https://github.com/aeternity/aepp-sdk-js/pull/1365
https://github.com/aeternity/aepp-sdk-js/pull/1371
https://github.com/aeternity/aepp-sdk-js/issues/1382
