### ISSUE TITLE
execute a specific test file

### ISSUE THREAD

**Issue by marc0olo** [aeternity/aeproject#403]
not sure if this is currently possible. in the past I was able to do that and in larger repositories (e.g. our [aepp-sophia-examples](https://github.com/aeternity/aepp-sophia-examples)) it would be good being able to execute only specific test files.

I tested with `v4.0.0-beta.3`

**Comment by thepiwo** [comment]
testing is done using mocha, e.g. via a different file pattern or https://mochajs.org/#-grep-regexp-g-regexp
