### ISSUE TITLE
`aeproject env --stop` doesn't work if node is stopped

### ISSUE THREAD

**Issue by marc0olo** [aeternity/aeproject#411]
aeproject tells me the env is not running. but nginx and compiler are still running. I think we should cover all containers with this command

```sh
marc0olo@DESKTOP-B1QLEDL:~/git/aeternity/aepp-sophia-examples$ npm run env:stop

> aepp-sophia-examples@1.0.0 env:stop
> aeproject env --stop

===== Env is not running! =====
marc0olo@DESKTOP-B1QLEDL:~/git/aeternity/aepp-sophia-examples$ docker ps
CONTAINER ID   IMAGE                            COMMAND                  CREATED          STATUS                    PORTS                            NAMES
caebe103a12f   nginx:latest                     "/docker-entrypoint.…"   31 minutes ago   Up 31 minutes             80/tcp, 0.0.0.0:3001->3001/tcp   aepp-sophia-examples-aeproject_proxy-1
fb1d9a285e99   aeternity/aesophia_http:latest   "/docker-entrypoint.…"   31 minutes ago   Up 31 minutes (healthy)   0.0.0.0:3080->3080/tcp           aepp-sophia-examples-aeproject_compiler-1
```

**Comment by thepiwo** [comment]
can you retry `aeproject env`, `aeproject env --stop` there is nothing specific to just stopping single containers in the code

**Comment by marc0olo** [comment]
> can you retry `aeproject env`, `aeproject env --stop` there is nothing specific to just stopping single containers in the code

well, yeah if I restart the node with the sequence you mentioned it works. it's just like when the node crashes for some reason `aeproject env --stop` doesn't work.

starting it up again and then stopping the env works
