### ISSUE TITLE
Tx Nonce Too High For Account

### ISSUE THREAD

**Issue by VitalJeevanjot** [aeternity/aeproject#417]
**Describe the bug**
Whenever I perform a `send` transaction 2nd time through Test, I get this error `tx_nonce_too_high_for_account`. I need to restart node with aeproject env --stop and aeproject env each time to perform another send transaction.

**To Reproduce**
1. Go to ['repo'](https://github.com/genievot/zk-ae-private-transactions/tree/errors_tracking) (errors_tracking branch)
2. Run test `aeproject test` on this repo
3. See error

**Expected behavior**
It shouldn't produce this error (auto adjust nonce for local testnet if required)

**Screenshots**
![image](https://user-images.githubusercontent.com/40867747/173213683-7034ec20-9e35-4e9b-96f3-32628a2c02e3.png)

**Please tell us about your environment:**

  - Node Version: v14.18.3
  - Aeproject Version: 4.0.0
  - Compiler version: From Aeproject
  - VM Version: From Aeproject
  - Python version: v3.7.5

stack traces:
```
/<repo>/node_modules/@aeternity/aepp-sdk/dist/aepp-sdk.js:1:68755
      at Array.forEach (<anonymous>)
      at Object.Ys (node_modules/@aeternity/aepp-sdk/dist/aepp-sdk.js:1:68589)
      at processTicksAndRejections (internal/process/task_queues.js:95:5)
```

**Comment by thepiwo** [comment]
either something is not properly awaited or this is a bug in the sdk

**Comment by thepiwo** [comment]
aeproject just uses the sdk for this, so the bug will probably be there if any
