### ISSUE TITLE
TxTimedOutError: giving up after 10 blocks mined...

### ISSUE THREAD

**Issue by VitalJeevanjot** [aeternity/aeproject#418]
**Describe the bug**
When I try with contract function **send** method with gas settings even with this high `{ gas: 200000000, gasPrice: 20000000000 }`, I get `TxTimedOutError: Giving up after 10 blocks mined, transaction hash: <hash>` .

**To Reproduce**
1. Go to ['repo'](https://github.com/genievot/zk-ae-private-transactions/tree/errors_tracking) (errors_tracking branch)
2. Run test `aeproject test` on this repo
3. See error

**Expected behavior**
I am not sure, But send transaction should pass on functions that don't require state changes, right ?

**Screenshots**
![image](https://user-images.githubusercontent.com/40867747/173216902-36b34000-ea79-4508-8f40-5613627415b0.png)

**Please tell us about your environment:**

  - Node Version: v14.18.3
  - Aeproject Version: 4.0.0
  - Compiler version: From Aeproject
  - VM Version: From Aeproject
  - Python version: v3.7.5

stack traces (including message)
```
TxTimedOutError: Giving up after 10 blocks mined, transaction hash: th_Sdwsf76nbtsQF4v9aE6YU7E4ECeDXSBidmZNHkkYZWPJE9rc4
      at Object.poll (node_modules/@aeternity/aepp-sdk/dist/aepp-sdk.js:1:71371)
      at processTicksAndRejections (internal/process/task_queues.js:95:5)
      at async Object.sendTransaction (node_modules/@aeternity/aepp-sdk/dist/aepp-sdk.js:1:69402)
      at async d (node_modules/@aeternity/aepp-sdk/dist/aepp-sdk.js:1:93902)
      at async Object.c.call (node_modules/@aeternity/aepp-sdk/dist/aepp-sdk.js:1:97145)
      at async Context.<anonymous> (test/mimcSpongeTest.js:43:17)
```

**Comment by thepiwo** [comment]
I don't think this is an aeproject error, have you tried dry-running and checked what the expected gas-consumption is?

**Comment by genievot** [comment]
I did dry run and it does works with abstracted max settings as `{ gas: 59000000, gasPrice: 20000000000 }` setting it to 60000000 gets me `over the gas limit` error. The case originated from here https://forum.aeternity.com/t/how-to-make-it-less-gas-intensive-try-to-run-mimcfeistel-with-220-2-0-0/10656/9?u=genievot

**Comment by thepiwo** [comment]
for microblocks there is a gas limit of 6000000, thats probably why it won't get picked up

**Comment by genievot** [comment]
got it but for `send()` this (low gas) or high both gives this error.

**Comment by genievot** [comment]
Also, It might work fine if you don't give extra parameters like gas, gasPrice with send function.

**Comment by VitalJeevanjot** [comment]
thanks!
