### ISSUE TITLE
Only 24 elements are returning instead of all the array

### ISSUE THREAD

**Issue by VitalJeevanjot** [aeternity/aeproject#419]
**Describe the bug**
I want to convert number of bytes array to integer through the contract (one time operation). But I get only 24 of them returned at max. Either with dry-run or send operation the result is same. Calling the original `zeros()` (as entrypoint) return only 24 bytes an not the full array.

Through ae editor (online). I get all 32 returned, but with `aeproject test` only 24.

**To Reproduce**
1. Go to [repo get_int branch](https://github.com/genievot/zk-ae-private-transactions/tree/get_int)
2. Run `aeproject test` 

**OR**

1. Copy [MerkleTreeWithHistory](https://github.com/genievot/zk-ae-private-transactions/blob/get_int/contracts/MerkleTreeWithHistory.aes)
2. Run test described in [test file](https://github.com/genievot/zk-ae-private-transactions/blob/get_int/test/merkleTreeHistoryTest.js#L42)

**Expected behavior**
The test console log (if possible) should return all of the array (either original or processed).

**Screenshots**
![image](https://user-images.githubusercontent.com/40867747/173568855-b3ae321f-d8b9-429c-8bd1-77c089d940e5.png)

![image](https://user-images.githubusercontent.com/40867747/173569042-55487ec1-34ce-49ff-a737-48713534e121.png)

Please tell us about your environment:

  - Node Version: v14.18.3
  - Aeproject Version: 4.0.0
  - Compiler version: From Aeproject
  - VM Version: From Aeproject
  - Python version: v3.7.5

**Comment by VitalJeevanjot** [comment]
@marc0olo @thepiwo please take a look at this, I tried it with latest push on the main, https://github.com/VitalJeevanjot/zk-ae-private-transactions/tree/main
Even with sdk v12 (through scripts testing), For e.g. I am receiving `[]` from https://github.com/VitalJeevanjot/zk-ae-private-transactions/blob/main/contracts/MerkleTreeWithHistory.aes#L34 which is just 21 in length array.

**Comment by thepiwo** [comment]
aeproject just uses the sdk for this, so the bug will probably be there if any
