### ISSUE TITLE
Make generated projects compatible with `docker-compose up` out of the box

### ISSUE THREAD

**Issue by davidyuk** [aeternity/aeproject#431]
**Is your feature request related to a problem? Please describe.**

As I understand `aeproject` generates `docker-compose.yml` file that depends on `NODE_TAG` and `COMPILER_TAG` env variables. I would like to use `docker-compose up` to run the testing environment as a more familiar tool for me, but it is not working untill I define these variables by myself (I'm creating an `.env` file).

Would be nice if aeproject specify some version of node and compiler to be compatible with `docker-compose` out of the box.

**Describe the solution you'd like**

aeproject can create `.env` file by itself, not sure how to handle this in the best way.

**Comment by thepiwo** [comment]
What do you think of this solution? https://github.com/aeternity/aeproject/pull/432

**Comment by marc0olo** [comment]
I also wanted to see that. didn't check the solution, but if it works go with it! :)
