### ISSUE TITLE
Consider Aeproject Debug Mode with additional log output

### ISSUE THREAD

**Issue by davidyuk** [aeternity/aeproject#435]
**Put `console.log` in `getFilesystem` under a debug flag or remove 🤷‍♀️**

I'm going to use `getFilesystem` in cli and the problem is that cli have a JSON-only output mode and I have to apply a workaround like
```js
    const originalConsoleLog = console.log;
    console.log = () => {};
    let fs = utils.getFilesystem(contractSourcePath);
    console.log = originalConsoleLog;
```
to don't break output JSON structure due to "Adding include to filesystem" message

**Comment by thepiwo** [comment]
Sounds like something that should be there in general for some reason or the other. For this case and current state it will be easy to copy the module code somewhere else and add the required logs there.

**Comment by thepiwo** [comment]
@davidyuk can this be closed as getFilesystem has an implementation in the sdk now?

**Comment by davidyuk** [comment]
Yep! https://docs.aeternity.com/aepp-sdk-js/v13.2.1/api/functions/getFileSystem.html
