### ISSUE TITLE
Apple M2 use version 4.6.1 eroor

### ISSUE THREAD

**Issue by sunbx** [aeternity/aeproject#466]
![image](https://github.com/aeternity/aeproject/assets/8652427/c6047a3e-67d4-4b5c-808a-b411bc355ac8)
<img width="1074" alt="image" src="https://github.com/aeternity/aeproject/assets/8652427/ee0f83e9-fc0a-414a-a0eb-b7590d8ea998">
<img width="1075" alt="image" src="https://github.com/aeternity/aeproject/assets/8652427/532d20b0-0517-4b36-83a8-e14a37db68e4">

**Comment by sunbx** [comment]
1.use aeprject version 4.6.1
2.aeproject init box-dice-contract
3.aearoject env

node version 16
<img width="267" alt="image" src="https://github.com/aeternity/aeproject/assets/8652427/51d210cd-d7a6-4f2a-a63e-fac302b96667">

**Comment by thepiwo** [comment]
As it's closed does it mean the issue is resolved?

**Comment by sunbx** [comment]
@thepiwo @marc0olo Yes, it was perfect. I rebooted the computer once and it magically stopped reporting errors 😁
