### ISSUE TITLE
`utils.rollbackHeight` rolls back to wrong height

### ISSUE THREAD

**Issue by marc0olo** [aeternity/aeproject#493]
**Describe the bug**
Following testcode:

```js
    // rollback to first keyblock
    await utils.rollbackHeight(aeSdk, 1);
    assert.equal(await aeSdk.getHeight(), 1);
```

Fails with:

```sh
AssertionError: expected 2 to equal 1
      + expected - actual

      -2
      +1
```

**Expected behavior**
I expect the assertion to pass, currently it fails.

**Please tell us about your environment:**

  - AEproject version: `v4.8.2`
  - Devmode version: `v0.5.2`

**Comment by thepiwo** [comment]
https://github.com/aeternity/aeproject/pull/483/files

**Comment by thepiwo** [comment]
It will need some additional debugging to know where exactly the need for this workaround is originating

**Comment by marc0olo** [comment]
ahhh, now I remember we already had some discussion about that 😅

**Comment by marc0olo** [comment]
I get a consistent behavior in my tests when executing the following code sequence in my tests:

```js
    // rollback to first keyblock
    await utils.rollbackHeight(aeSdk, 0);
    // stupid but strange, opened an issue here: https://github.com/aeternity/aeproject/issues/493
    assert.equal(await aeSdk.getHeight(), 2);

    // activate iris
    await utils.awaitKeyBlocks(aeSdk, 3);
    assert.equal(await aeSdk.getHeight(), 5);
    let nodeInfo = await aeSdk.getNodeInfo();
    assert.equal(nodeInfo.consensusProtocolVersion, 5);
```

it seems like the node is setting keyblock = 1 when performing the rollback to height 0, given that `rollbackHeight` in aeproject executes following logic:
```js
export const rollbackHeight = async (aeSdk, height) => {
  const currentBlockHeight = await aeSdk.getHeight();
  if (currentBlockHeight > height) {
    await get(`http://localhost:3001/rollback?height=${height}`);
    await awaitKeyBlocks(aeSdk, 1);
  }
};
```

**Comment by thepiwo** [comment]
this still seems to happen, experienced it again, also @hanssv did, using `await awaitKeyBlocks(aeSdk, 1);` after creating the snapshot seems to help, will investigate as I think the issue is in the underlaying devmode
